
### GET ALL
GET http://localhost:3001/api/blogs

### POST REQUEST
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title":"Hello World",
  "author":"Jan Haubrock",
  "url":"http://www.jan-haubrock.de/blog",
  "likes":30
}

### POST REQUEST with Authorization
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhdWkiLCJpZCI6IjYyNTU0ZTYzM2M2NjRjZmM2MWJkNmRlMiIsImlhdCI6MTY1MDIxMTc3MCwiZXhwIjoxNjUwMjE1MzcwfQ.7o_uFwVgpNdknHJIakHNEQ9jfpYYEp2AZxHc9LSflxM

{
  "title":"Katzenklo macht die Katze froh!",
  "author":"Jan Haubrock",
  "url":"http://www.jan-haubrock.de/blog",
  "likes":30
}

### POST REQUEST Missing URL
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title":"Hello World",
  "author":"Jan Haubrock"
}

### POST REQUEST Missing Title
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author":"Jan Haubrock",
  "url":"http://www.jan-haubrock.de/blog" 
}

### POST REQUEST Missing Likes
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author":"Jan Haubrock",
  "url":"http://www.jan-haubrock.de/blog",
  "title":"Who you gonna call"
}

### PUT Request with ID
PUT http://localhost:3001/api/blogs/624a228a2039b0b796859cbf
Content-Type: application/json

{
  "author" :"Edsger W. Dijkstra",
  "likes":"15"
}

### Delete Request without Authorization
DELETE http://localhost:3001/api/blogs/625c3812f6c4965d8a10736c
Content-Type: application/json


### Delete Request with Authorization
DELETE http://localhost:3001/api/blogs/625c4083e4c76145629f9ecb
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhdWkiLCJpZCI6IjYyNTU0ZTYzM2M2NjRjZmM2MWJkNmRlMiIsImlhdCI6MTY1MDIxMDQ1MCwiZXhwIjoxNjUwMjE0MDUwfQ.egAy5fgEkD6NelysuJMmDuvFQQI6_690t27EMpuJaB4



### Delete Request with wrong user Authorization
DELETE http://localhost:3001/api/blogs/625c4083e4c76145629f9ecb
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhdWkyIiwiaWQiOiI2MjVjM2I5OWJmNTM1MmIwYjk3MzgzY2MiLCJpYXQiOjE2NTAyMTE4MjUsImV4cCI6MTY1MDIxNTQyNX0.GqCiOzj6_adq6BEqQDOlIoWaz5orOhcwB4wbASoxu3M